### ISSUE TITLE
GitHub action: actions-cloudflare-purge

### ISSUE THREAD

**Issue by sadikkuzu** [alpaylan/afetbilgi.com#151]
Merhaba,

Cloudflare için ayrı bir action oluşturulabilir mi?

`purge-cloudflare-cache.yaml`

```yaml
name: Purge cloudflare cache manually

on:
  workflow_dispatch:

  # schedule:
  #   - cron: "32 * * * *"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v3

      - name: Purge cache
        uses: nathanvaughn/actions-cloudflare-purge@v3.1.0
        with:
          cf_zone: ${{ secrets.CLOUDFLARE_ZONE }}
          cf_auth: ${{ secrets.CLOUDFLARE_AUTH_KEY }}
          hosts: |
            pdf.afetbilgi.com
            cdn.afetbilgi.com

```

Aşağıdaki gibi kalan durumlarda
pdfler synclenmiş olduğu için
tekrar pdf üretmeden manual cache purge yapabiliriz:

[![image](https://user-images.githubusercontent.com/23168063/218274035-3d15dff9-46a8-4ac9-ae7b-6a9c4c25c1b7.png)}](https://github.com/alpaylan/afetbilgi.com/actions/runs/4152434383/jobs/7183387190)
